### ISSUE TITLE
[Steps variants] Steps variants text is overlapping the bottom of the window

### ISSUE THREAD

**Issue by Marketionist** [alexkrechik/featuresGenerator#35]
**STR**
1. Click on the "Auto steps complete" checkbox
2. Fill in any text in the "Generated steps" input to see all possible variants in the "Steps variants" section
3. Scroll down to the bottom of "Steps variants" section

**AR**
Steps variants text is overlapping the bottom of the window - see the screenshot below
![suggested_steps_overlapping](https://cloud.githubusercontent.com/assets/534603/17272380/cd6cdaaa-569d-11e6-85ba-64fc768449b9.png)
**ER**
Steps variants text is displayed properly inside its section

**Comment by alexkrechik** [comment]
Fixed

**Comment by alexkrechik** [comment]
Dmitriy, please retest.

**Comment by Marketionist** [comment]
Tested on recent master - works ok now.
